require 'config.vim'
require 'config.plugins'
require 'config.telescope'
require 'config.treesitter'
require 'config.completion'
require 'config.lsp'
require 'config.tabular'
require 'config.statusline'
vim.cmd('colorscheme edge')
