autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
setopt COMPLETE_ALIASES
alias ls='ls --color=auto'

source $HOME/.dotfiles/zsh/custom-functions.sh
source $HOME/.dotfiles/zsh/prompt.sh

if [  $(command -v ag) ]; then
    export FZF_DEFAULT_COMMAND='ag -l -g ""'
else
    export FZF_DEFAULT_COMMAND="find $CWD -type f | grep -v log | grep -v node_modules | grep -v .git | grep -v vendor | sort"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zsh-local.sh ] && source ~/.zsh-local.sh
